version: 0.2
        
phases:
  pre_build:
    commands:
      - chmod +x create-or-update-stack.sh
      - ./create-or-update-stack.sh us-east-1 brewery-app-stack --template-body file://cloudformation.yaml
  #   finally:
  #     - command
  #     - command
  # build:
  #   run-as: Linux-user-name
  #   on-failure: ABORT | CONTINUE
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
  # post_build:
  #   run-as: Linux-user-name
  #   on-failure: ABORT | CONTINUE
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
